//
//  CMRsaDecryptor.h
//
//  Created by Charles Krutsinger on 1/22/15.
//
//  Copyright (c) 2015 Countermind. All rights reserved.
//
//  makes use of a self-signed certificate pair generated by
//  openssl req -x509 -out public_key.pem -outform PEM -new -newkey rsa:4096 -keyout private_key.pem -keyform PEM -days 3650
//  openssl pkcs12 -export -in public_key.pem -inkey private_key.pem -out private_key.p12
//  openssl x509 -in public_key.pem -inform PEM -out public_key.crt -outform DER
//  passphrase countermind
//
//  By default, in iOS public keys cannot be used to decrypt.

@interface CMRsaDecryptor : NSObject

/**
 *  Initialize RSA object with a p12 file containing the private key.
 *
 *  @param tPrivateKeyPath path to private key file in p12 format
 *  @param tPasscode passcode to open p12 file
 *
 *  @return instance
 */
- (CMRsaDecryptor *)initWithPrivateKey:(NSString *)tPrivateKeyPath withPassphrase:(NSString *)tPassphrase;

/**
 *  Decrypt base 64 string using RSA encryption
 *
 *  @param tCipherString base 64 encoded encrypted string
 *
 *  @return plain text
 */
-(NSString *)decryptRSA:(NSString *)tCipherString;

@end
